# Title of your blog; shows in the header
name: "Ana Balica"

# Description of your content (will only be used on Google Search)
description: "Blog about code, traveling and social involvement"

# Your name. Will show in your footer + sidebar
author: "Ana"

url: "http://ana-balica.github.io"
baseurl: ""

author-bio: "I'm a software developer. I mostly do Python.
This blog is about my adventures with code, travel experiences and relevant life events.
I try not to take myself too seriously.

<p>Here's what I'm doing <a href='/now/'>now</a>.</p>

<p>Occasionally I give <a href='/talks/'>talks</a>.</p>

<p><em>Please don't take my words for granted, because Internet is full of bad advice, and I might be part of it inadvertently.</em></p>"

ga_domain: ana-balica.github.io
ga_tracking_id: UA-52365795-1

markdown: kramdown
permalink: pretty

paginate: 10
paginate_path: "/page/:num"

sass:
  sass_dir: _scss
  style: :compressed

kramdown:
  auto_ids: true
