# Title of your blog; shows in the header
name: "Ana Balica"

# Description of your content (will only be used on Google Search)
description: "Blog about code, traveling and social involvement"

# Your name. Will show in your footer + sidebar
author: "Ana"

url: "http://ana-balica.github.io"
baseurl: ""

# A short presentation of yourself. Will show in the sidebar, under your name. Best usage would be between 30 to 50 words.
author-bio: "I'm a software developer. I work at <a href='https://p.ota.to' target='_blank'>Potato</a>.
This blog is about my adventures with code, travel experiences and relevant life events. I like Python, books and cats.\n
Occasionally I give <a href='/talks.html'>talks</a>.

<p><em>Please don't take my words for granted, because Internet is full of bad advice, and I might be part of it unknownligly.</em></p>"

# Google Analytics (you may want to changes these with yours or even delete :)

ga_domain: ana-balica.github.io
ga_tracking_id: UA-52365795-1

# Other (refer to http://jekyllrb.com/docs/home/ for further details on the below)

markdown: kramdown
permalink: pretty

paginate: 10
paginate_path: "/page/:num"

# SCSS

sass:
  sass_dir: _scss
  style: :compressed
